# Generated by Django 5.1.1 on 2024-11-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_like_count_user_followers_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers_count',
            new_name='follower_count',
        ),
    ]
