# Generated by Django 5.1.1 on 2024-11-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_followers_count_user_follower_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follower_count',
        ),
    ]
